DEREF_FAULT: print hex better, without #token
With deref() constructs being nested, the expression parameters is now
frequently generated C goo that a stap user cannot be expected to understand.
We no longer print that part in the DEREF_FAULT handler, leaving only the
faulting address.

Before:

ERROR: read fault [man error::fault] at 0x          (null) ((({ u64 _v; int _e = _stp_deref_nofault_(&_v, (8), (void *)(unsigned long)((((l->l__fb_0) + (((int64_t)-96LL))))), (((mm_segment_t) { (((1UL << 47) - ((1UL) << 12))) }))); if (_e) ({ snprintf(c-

After:

ERROR: read fault [man error::fault] at 0x0 near identifier '$j' at ../../systemtap2/testsuite/systemtap.base/implicitptr.stp:4:7